export const Users = [
  {
    id:1,
    profileImg: "assets/person/1.jpg",
    username: "Ray Barson",
  },
  {
    id:2,
    profileImg: "assets/person/2.jpg",
    username: "Jessica Holmes",
  },
  {
    id:3,
    profileImg: "assets/person/3.jpg",
    username: "John Fisher",
  },
  {
    id:4,
    profileImg: "assets/person/4.jpg",
    username: "Gese Zimmermann",
  },
  {
    id:5,
    profileImg: "assets/person/5.jpg",
    username: "Thomas Holden",
  },
  {
    id:6,
    profileImg: "assets/person/6.jpg",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profileImg: "assets/person/7.jpg",
    username: "Selena Potts",
  },
  {
    id:8,
    profileImg: "assets/person/8.jpg",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profileImg: "assets/person/9.jpg",
    username: "Gary Duty",
  },
  {
    id:10,
    profileImg: "assets/person/10.jpg",
    username: "Laurie Price",
  },
  {
    id:11,
    profileImg: "assets/person/11.jpg",
    username: "Leah Berrotti",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "My motive from now on.",
    photo: "assets/post/1.jpg",
    date: "5 mins ago",
    userId: 5,
    like: 41,
    comment: 9,
  },
  {
    id: 2,
    desc: "Love what I have!!",
    photo: "assets/post/2.jpg",
    date: "15 mins ago",
    userId: 11,
    like: 78,
    comment: 12,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpg",
    date: "1 hour ago",
    userId: 7,
    like: 42,
    comment: 14,
  },
  {
    id: 4,
    desc: "Ready for what to come!",
    photo: "assets/post/4.jpg",
    date: "4 hours ago",
    userId: 9,
    like: 17,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpg",
    date: "5 hours ago",
    userId: 7,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    desc: "running, running and running away!!!",
    photo: "assets/post/6.jpg",
    date: "1 day ago",
    userId: 10,
    like: 414,
    comment: 66,
  },
  {
    id: 7,
    desc: "Enjoying life how it is!!",
    photo: "assets/post/7.jpg",
    date: "2 days ago",
    userId: 4,
    like: 122,
    comment: 31,
  },
  {
    id: 8,
    desc: "life right now is just: \"WORK WORK WORK\" !!",
    photo: "assets/post/8.jpg",
    date: "3 days ago",
    userId: 4,
    like: 115,
    comment: 12,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpg",
    date: "5 days ago",
    userId: 5,
    like: 121,
    comment: 61,
  },
  {
    id: 10,
    photo: "assets/post/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
  {
    id: 11,
    desc: "Just do what it says.",
    photo: "assets/post/11.jpg",
    date: "1 week ago",
    userId: 8,
    like: 141,
    comment: 81,
  },
];